# First ensure that the user has correctly created a sc_env.mk file by running the init-repo script
$(info Checking for ScuffedCraft environment configuration file)
ifeq (,$(wildcard ./build/sc_env.mk))
$(error Could not find environment configuration file, ensure one exists in build/sc_env.mk)
else
$(info Found!)
endif

# The user has an environment config, so souce it for its variables
include build/sc_env.mk
$(info Using DevkitPro path : $(DEVKITPRO))

# Check that the user has the compiler 
ifeq (, $(wildcard $(DEVKITPPC)/bin/powerpc-eabi-gcc))
$(error Could not find compiler at the right path. Check build/sc_env.mk)
else
$(info Compiler path : $(DEVKITPPC)/bin/powerpc-eabi-gcc)
CC = $(DEVKITPPC)/bin/powerpc-eabi-gcc
endif

# Define the default target which is to build the Scuffedcraft release, which depends on the Scuffedcraft.elf
ScuffedCraft.dol: ScuffedCraft.elf
	@echo "Compiling release configuration"
	@echo $(SC_DOLPHIN_CMD)

# The scuffedcraft.elf target is dependent on all the object files, the object files are generated by the source
# So we need to pull in the source directory's make file, to get a list of all the object files 
# For now just use a force target to always update the elf component
ScuffedCraft.elf: FORCE
	@echo "Building ScuffedCraft ..."

FORCE: ;