/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _albedo_cube_h_
#define _albedo_cube_h_
//---------------------------------------------------------------------------------
extern const unsigned char albedo_cube[];
extern const int albedo_cube_size;
//---------------------------------------------------------------------------------
#endif //_albedo_cube_h_
//---------------------------------------------------------------------------------
